version: '3'

services:
  sap_api:
    container_name: sap_api
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
